### PR TITLE
[WIP] CLI bats integration tests

### PR DESCRIPTION
**Pull request by whilei**
Run: `bats cli.bats`

TODO:
- [ ] write more tests
- [ ] include in CI builds

### CODE REVIEW

**Comment by whilei** [comment]
Bats test performing differently for CI Linux than my local OSX machine:

Local: 
```
~/dev/etc/emerald-cli tests/cli-bats ⟠ bats cli.bats
 ✓ [meta] succeeds: set env var and tmp dir EMERALD_BASE_PATH
 ✓ succeeds: --version
 ✓ succeeds: --help
 ✓ succeeds: new --chain=testnet [empty options]
 ✓ succeeds: new --chain=mainnet --security=high --name='Test account' --description='Some description'
 ✓ succeeds: list
 ✓ succeeds: update
 ✓ succeeds: strip
 ✓ succeeds: hide && unhide

9 tests, 0 failures
```

CI: https://travis-ci.org/ethereumproject/emerald-cli/jobs/273274694
```
14.33s$ bats cli.bats
1..9
ok 1 [meta] succeeds: set env var and tmp dir EMERALD_BASE_PATH
ok 2 succeeds: --version
ok 3 succeeds: --help
ok 4 succeeds: new --chain=testnet [empty options]
ok 5 succeeds: new --chain=mainnet --security=high --name='Test account' --description='Some description'
ok 6 succeeds: list
not ok 7 succeeds: update
# (in test file cli.bats, line 102)
#   `[ "$status" -eq 0 ]' failed
ok 8 succeeds: strip
not ok 9 succeeds: hide && unhide
# (in test file cli.bats, line 155)
#   `[ "$status" -eq 0 ]' failed
The command "bats cli.bats" exited with 1.
```

**Comment by r8d8** [comment]
Will test on my local linux,

**Comment by r8d8** [comment]
2017-09-12-175433_1600x900_scrot

**Comment by whilei** [comment]
`update`, `hide`, and `unhide` don't require password input, right?

**Comment by r8d8** [comment]
yeap, no password required

**Comment by r8d8** [comment]
Merged in new PR #21

**Pull request closed without merging**
